username: '13121552460'

password: 'yinshao1206'

# 演唱会详情页面URL
ticket_url: 'https://m.damai.cn/shows/item.html?from=def&itemId=766688730814&sqm=dianying.h5.unknown.value&spm=a2o71.search.list.ditem_1'

# 购买哪个站点
ticket_site: "郑州站"

# 场次日期
ticket_date: "2024-03-23"

# 票档
ticket_grade: "内场999元"

# 购买数量
ticket_num: 2

# 实名人名字, 没有相同姓氏只写姓即可，否则写完整姓名. 实名人数量需要与购票数量一致
real_names:
  - 尹孟琦
  - 孙艳娜

